codes = {0:	['tornado', '../images/thunder-storm.png'],
1: ['tropical storm' ,'../images/thunder-storm.png'],
2:	['hurricane',	'../images/thunder-storm.png'],
3:	['severe thunderstorms',	'../images/thunder-storm.png'],
4:	['thunderstorms',	'../images/thunder-storm.png'],
5:	['mixed rain and snow',	'../images/rainy-snow.png'],
6:	['mixed rain and sleet',	'../images/rainy-snow.png'],
7:	['mixed snow and sleet',	'../images/rainy-snow.png'],
8:	['freezing drizzle',	'../images/freezing-rain.png'],
9:	['drizzle',	'../images/drizzle.png'],
10:	['freezing rain',	'../images/freezing-rain.png'],
11:	['showers',	'../images/showers.png'],
12:	['showers',	'../images/showers.png'],
13:	['snow flurries',	'../images/snow-shower.png'],
14:	['light snow showers',	'../images/snow.png'],
15:	['blowing snow',	'../images/blowing-snow.png'],
16:	['snow',	'../images/snow.png'],
17:	['hail',	'../images/sleet.png'],
18:	['sleet',	'../images/sleet.png'],
19:	['dust',	'../images/smoke.png'],
20:	['foggy',	'../images/fog.png'],
21:	['haze',	'../images/haze.png'],
22:	['smoky',	'../images/smoke.png'],
23:	['blustery',	'../images/wind.png'],
24:	['windy',	'../images/wind.png'],
25:	['cold',	'../images/wind.png'],
26:	['cloudy',	'../images/cloudy.png'],
27:	['mostly cloudy (night)',	'../images/p-c night.png'],
28:	['mostly cloudy (day)',	'../images/partly-cloudy.png'],
29:	['partly cloudy (night)',	'../images/p-c night.png'],
30:	['partly cloudy (day)',	'../images/partly-cloudy.png'],
31:	['clear (night)',	'../images/moon.png'],
32:	['sunny',	'../images/sunny.png'],
33:	['fair (night)',	'../images/fair.png'],
34:	['fair (day)',	'../images/fair.png'],
35:	['mixed rain and hail',	'../images/rainy-snow.png'],
36:	['hot',	'../images/sunny.png'],
37:	['isolated thunderstorms',	'../images/thunder-storm.png'],
38:	['scattered thunderstorms',	'../images/thunder-storm.png'],
39:	['scattered thunderstorms',	'../images/thunder-storm.png'],
40:	['scattered showers',	'../images/m-c rain.png'],
41:	['heavy snow',	'../images/snow.png'],
42:	['scattered snow showers',	'../images/m-c snow.png'],
43:	['heavy snow',	'../images/snow.png'],
44:	['partly cloudy',	'../images/partly-cloudy.png'],
45:	['thundershowers',	'../images/t-storm-rain.png'],
46:	['snow showers',	'../images/snow-shower.png'],
47:	['isolated thundershowers',	'../images/thunder-storm.png'],
3200: ['not available',	'../images/na.png']}

codes_des = {'tornado':'../images/thunder-storm.png',
'tropical storm':'../images/thunder-storm.png',
'hurricane':'../images/thunder-storm.png',
'severe thunderstorms':'../images/thunder-storm.png',
'thunderstorms':'../images/thunder-storm.png',
'mixed rain and snow':'../images/rainy-snow.png',
'mixed rain and sleet':'../images/rainy-snow.png',
'mixed snow and sleet':'../images/rainy-snow.png',
'freezing drizzle':'../images/freezing-rain.png',
'drizzle':'../images/drizzle.png',
'freezing rain':'../images/freezing-rain.png',
'showers':'../images/showers.png',
'rain': '../images/showers.png',
'Scattered Showers': '../images/showers.png',
'snow flurries':'../images/snow-shower.png',
'light snow showers':'../images/snow.png',
'blowing snow':'../images/blowing-snow.png',
'snow':'../images/snow.png',
'hail':'../images/sleet.png',
'sleet':'../images/sleet.png',
'dust':'../images/smoke.png',
'foggy':'../images/fog.png',
'haze':'../images/haze.png',
'smoky':'../images/smoke.png',
'breezy': '../images/wing.png',
'blustery':'../images/wind.png',
'windy':'../images/wind.png',
'cold':'../images/wind.png',
'cloudy':'../images/cloudy.png',
'sunny': '../images/sunny.png',
'mostly sunny': '../images/m-cloudy.png',
'mostly cloudy':'../images/m-cloudy.png',
'partly cloudy':'../images/partly-cloudy.png',
'clear (night)':'../images/moon.png',
'fair (night)':'../images/fair.png',
'fair (day)':'../images/fair.png',
'mixed rain and hail':'../images/rainy-snow.png',
'hot':'../images/sunny.png',
'isolated thunderstorms':'../images/thunder-storm.png',
'scattered thunderstorms':'../images/thunder-storm.png',
'scattered thunderstorms':'../images/thunder-storm.png',
'scattered showers':'../images/m-c-rain.png',
'heavy snow':'../images/snow.png',
'scattered snow showers':'../images/m-c snow.png',
'heavy snow':'../images/snow.png',
'partly cloudy':'../images/partly-cloudy.png',
'thundershowers':'../images/t-storm-rain.png',
'snow showers':'../images/snow-shower.png',
'isolated thundershowers':'../images/thunder-storm.png',
'not available':'../images/na.png'}
