codes = {0:	['tornado', 'thunder-storm.png'],
1: ['tropical storm' ,'thunder-storm.png'],
2:	['hurricane',	'thunder-storm.png'],
3:	['severe thunderstorms',	'thunder-storm.png'],
4:	['thunderstorms',	'thunder-storm.png'],
5:	['mixed rain and snow',	'rainy-snow.png'],
6:	['mixed rain and sleet',	'rainy-snow.png'],
7:	['mixed snow and sleet',	'rainy-snow.png'],
8:	['freezing drizzle',	'freezing-rain.png'],
9:	['drizzle',	'drizzle.png'],
10:	['freezing rain',	'freezing-rain.png'],
11:	['showers',	'showers.png'],
12:	['showers',	'showers.png'],
13:	['snow flurries',	'snow-shower.png'],
14:	['light snow showers',	'snow.png'],
15:	['blowing snow',	'blowing-snow.png'],
16:	['snow',	'snow.png'],
17:	['hail',	'sleet.png'],
18:	['sleet',	'sleet.png'],
19:	['dust',	'smoke.png'],
20:	['foggy',	'fog.png'],
21:	['haze',	'haze.png'],
22:	['smoky',	'smoke.png'],
23:	['blustery',	'wind.png'],
24:	['windy',	'wind.png'],
25:	['cold',	'wind.png'],
26:	['cloudy',	'cloudy.png'],
27:	['mostly cloudy (night)',	'p-c night.png'],
28:	['mostly cloudy (day)',	'partly-cloudy.png'],
29:	['partly cloudy (night)',	'p-c night.png'],
30:	['partly cloudy (day)',	'partly-cloudy.png'],
31:	['clear (night)',	'moon.png'],
32:	['sunny',	'sunny.png'],
33:	['fair (night)',	'fair.png'],
34:	['fair (day)',	'fair.png'],
35:	['mixed rain and hail',	'rainy-snow.png'],
36:	['hot',	'sunny.png'],
37:	['isolated thunderstorms',	'thunder-storm.png'],
38:	['scattered thunderstorms',	'thunder-storm.png'],
39:	['scattered thunderstorms',	'thunder-storm.png'],
40:	['scattered showers',	'm-c rain.png'],
41:	['heavy snow',	'snow.png'],
42:	['scattered snow showers',	'm-c snow.png'],
43:	['heavy snow',	'snow.png'],
44:	['partly cloudy',	'partly-cloudy.png'],
45:	['thundershowers',	't-storm-rain.png'],
46:	['snow showers',	'snow-shower.png'],
47:	['isolated thundershowers',	'thunder-storm.png'],
3200: ['not available',	'na.png']}

codes_des = {'tornado':'thunder-storm.png',
'tropical storm':'thunder-storm.png',
'hurricane':'thunder-storm.png',
'severe thunderstorms':'thunder-storm.png',
'thunderstorms':'thunder-storm.png',
'mixed rain and snow':'rainy-snow.png',
'mixed rain and sleet':'rainy-snow.png',
'mixed snow and sleet':'rainy-snow.png',
'freezing drizzle':'freezing-rain.png',
'drizzle':'drizzle.png',
'freezing rain':'freezing-rain.png',
'showers':'showers.png',
'showers':'showers.png',
'snow flurries':'snow-shower.png',
'light snow showers':'snow.png',
'blowing snow':'blowing-snow.png',
'snow':'snow.png',
'hail':'sleet.png',
'sleet':'sleet.png',
'dust':'smoke.png',
'foggy':'fog.png',
'haze':'haze.png',
'smoky':'smoke.png',
'blustery':'wind.png',
'windy':'wind.png',
'cold':'wind.png',
'cloudy':'cloudy.png',
'sunny': 'sunny.png',
'mostly sunny': 'm-cloudy.png',
'mostly cloudy':'m-cloudy.png',
'partly cloudy':'partly-cloudy.png',
'clear (night)':'moon.png',
'fair (night)':'fair.png',
'fair (day)':'fair.png',
'mixed rain and hail':'rainy-snow.png',
'hot':'sunny.png',
'isolated thunderstorms':'thunder-storm.png',
'scattered thunderstorms':'thunder-storm.png',
'scattered thunderstorms':'thunder-storm.png',
'scattered showers':'m-c rain.png',
'heavy snow':'snow.png',
'scattered snow showers':'m-c snow.png',
'heavy snow':'snow.png',
'partly cloudy':'partly-cloudy.png',
'thundershowers':'t-storm-rain.png',
'snow showers':'snow-shower.png',
'isolated thundershowers':'thunder-storm.png',
'not available':'na.png'}
